### ISSUE TITLE
关于国密算法ssl通信问题

### ISSUE THREAD

**Issue by AlexTan-b-z** [grantrepository/fabric_gm#1]
- 第一个问题：不知道作者是否用过此版本动态添加过orderer节点，在添加orderer节点时，会报orderer中tls目录下的server.crt证书错误：`server TLS certificate has invalid ASN1 structure`
- 第二个问题：使用此命令验证证书文件：`openssl verify --verbose -CAfile cacerts/ca.org1.example.com-cert.pem signcerts/peer0.org1.example.com-cert.pem`，同样会报关于`ASN1`的错误

**Comment by grantrepository** [comment]
@AlexTan-b-z 问题一：证书是咋么生成的？
问题二：openssl支持国密不？

**Comment by AlexTan-b-z** [comment]
> @AlexTan-b-z 问题一：证书是咋么生成的？
证书是make release编译出来的cryptogen生成的
> 问题二：openssl支持国密不？
用北大开源的那个gmssl报同样的错，之前用openssl 试过官方未改国密的cryptogen生成的证书verify能通过

**Comment by grantrepository** [comment]
用例是官方raft共识3order测试过，可能同济库和北大标准有点出入吧，具体问题得你花时间看看，最近没搞涉及这块的。

**Comment by AlexTan-b-z** [comment]
3 ordered 添加过orderer节点吗？

**Comment by grantrepository** [comment]
这个没有。

**Comment by AlexTan-b-z** [comment]
哦哦 好的 谢谢

**Comment by AlexTan-b-z** [comment]
我是在添加orderer节点才会有这个错误，其他操作暂时没有发现问题
